/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import Clases.*;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Franco
 */
public class VistaAparatosXDuenio extends javax.swing.JInternalFrame {
   
    private Conexion con;
    private ClienteData cd;
    private AparatoData ad;
    private ReparacionData rd;
    private List<Cliente> listaCliente;
    private List<Aparato> listaAparato;
    private DefaultTableModel modelo;
    /**
     * Creates new form VistaAparatosXDuenio
     */
    public VistaAparatosXDuenio() {
        initComponents();
        try {    
            con = new Conexion("jdbc:mysql://localhost/tallerreparacion","root","");
            cd = new ClienteData(con);
            ad = new AparatoData(con);
            rd = new ReparacionData(con);
            listaCliente = cd.listarClientes();
            listaAparato = ad.listarAparatos();
            modelo = new DefaultTableModel();
           cargarCombo();
           armarCabecera();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaAparato.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
    private void armarCabecera(){
        ArrayList<Object> columnas = new ArrayList<Object>();
        columnas.add("ID");
        columnas.add("Nro serie");
        columnas.add("Tipo");
        columnas.add("CLiente");
        columnas.add("Ingreso");
        columnas.add("Egreso");
        for(Object it:columnas)
        {
            modelo.addColumn(it);
        }
        jtAparatos.setModel(modelo);
    }
      private void borrarFilas(){
        int cant = modelo.getRowCount()-1;
        for(int i = cant ; i>=0;i--){
            modelo.removeRow(i);
        }
    }
    private void cargarTable() throws ClassNotFoundException{
        borrarFilas();
        Cliente selecciono = (Cliente) jcbClientes.getSelectedItem();
        listaAparato = ad.mostrarAparatosXduenio(selecciono.getIdCliente());
        for(Aparato a:listaAparato){
            modelo.addRow(new Object[]{a.getId_aparato(),a.getNro_serie(),a.getTipo(),a.getDueño().getNombre_Cliente(),a.getFechIngreso(),a.getFechEgreso()});
        }
    }
    private void cargarCombo(){
        listaCliente = cd.listarClientes();
        
        for(Cliente c: listaCliente){
            jcbClientes.addItem(c);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jcbClientes = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAparatos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbCalcular = new javax.swing.JButton();
        jlblCosto = new javax.swing.JLabel();

        setMaximizable(true);
        setResizable(true);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setText("APARATOS X DUEÑO");

        jcbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbClientesActionPerformed(evt);
            }
        });

        jtAparatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jtAparatos);

        jLabel1.setText("Clientes");

        jLabel2.setForeground(new java.awt.Color(0, 204, 153));
        jLabel2.setText("Seleccione un aparato para el costo total de los servicios!");

        jbCalcular.setText("Calcular");
        jbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcularActionPerformed(evt);
            }
        });

        jlblCosto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(177, 177, 177)
                            .addComponent(jLabel1)
                            .addGap(27, 27, 27)
                            .addComponent(jcbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(194, 194, 194)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jlblCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)))
                        .addComponent(jbCalcular)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jbCalcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblCosto, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbClientesActionPerformed
        try {
            // TODO add your handling code here:
            cargarTable();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaAparatosXDuenio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jcbClientesActionPerformed

    private void jbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcularActionPerformed
        try {
            // TODO add your handling code here:
            
            int row = jtAparatos.getSelectedRow();
            int idAparato = (int)jtAparatos.getValueAt(row, 0);
            
            double costo = rd.costoTotalAparato(idAparato);
            jlblCosto.setText("$"+ costo);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaAparatosXDuenio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbCalcularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCalcular;
    private javax.swing.JComboBox<Cliente> jcbClientes;
    private javax.swing.JLabel jlblCosto;
    private javax.swing.JTable jtAparatos;
    // End of variables declaration//GEN-END:variables
}
